import { SEO } from "@/components/SEO";
import { useState } from "react";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Label } from "@/components/ui/label";
import { Button } from "@/components/ui/button";
import { CheckCircle2, FileText, Printer, AlertTriangle } from "lucide-react";

export default function DocumentChecklist() {
  const [profession, setProfession] = useState("doctor");
  const [indianState, setIndianState] = useState("maharashtra");

  const printChecklist = () => {
    window.print();
  };

  return (
    <div className="w-full pb-20">
      <SEO 
        title="Document Checklist Generator | MediSpire"
        description="Generate a personalized checklist of documents required for German Approbation, customized for Indian doctors, dentists, and nurses."
        canonical="/tools/document-checklist"
      />

      <section className="bg-primary text-primary-foreground py-16 px-4 print:hidden">
        <div className="container mx-auto text-center max-w-3xl">
          <h1 className="text-4xl md:text-5xl font-bold mb-6">Document Checklist Generator</h1>
          <p className="text-xl text-primary-foreground/90">
            Never miss a document. Generate your exact list for German authorities, including MEA apostille and verification rules.
          </p>
        </div>
      </section>

      <section className="py-12 px-4 container mx-auto max-w-4xl">
        
        {/* Print only header */}
        <div className="hidden print:block mb-8 border-b-2 border-black pb-4">
          <h1 className="text-3xl font-bold">German Approbation Document Checklist</h1>
          <p>Generated by MediSpire Consultancy</p>
        </div>

        <div className="flex flex-col md:flex-row gap-8">
          
          {/* Controls - Hidden on print */}
          <div className="w-full md:w-1/3 space-y-6 print:hidden">
            <Card>
              <CardHeader>
                <CardTitle>Customize List</CardTitle>
                <CardDescription>Tailor the checklist to your profile.</CardDescription>
              </CardHeader>
              <CardContent className="space-y-4">
                <div className="space-y-2">
                  <Label>Profession</Label>
                  <Select value={profession} onValueChange={setProfession}>
                    <SelectTrigger>
                      <SelectValue placeholder="Select profession" />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="doctor">Doctor (MBBS/MD/MS)</SelectItem>
                      <SelectItem value="dentist">Dentist (BDS/MDS)</SelectItem>
                      <SelectItem value="nurse">Nurse (BSc/GNM)</SelectItem>
                    </SelectContent>
                  </Select>
                </div>
                
                <div className="space-y-2">
                  <Label>Registered State (India)</Label>
                  <Select value={indianState} onValueChange={setIndianState}>
                    <SelectTrigger>
                      <SelectValue placeholder="Select state" />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="maharashtra">Maharashtra (MMC)</SelectItem>
                      <SelectItem value="karnataka">Karnataka (KMC)</SelectItem>
                      <SelectItem value="kerala">Kerala (TCMC)</SelectItem>
                      <SelectItem value="delhi">Delhi (DMC)</SelectItem>
                      <SelectItem value="other">Other State Council</SelectItem>
                    </SelectContent>
                  </Select>
                </div>

                <Button onClick={printChecklist} variant="outline" className="w-full mt-4 flex items-center gap-2">
                  <Printer className="w-4 h-4" /> Print / Save PDF
                </Button>
              </CardContent>
            </Card>

            <div className="bg-amber-50 border-l-4 border-amber-500 p-4 rounded-r-lg">
              <div className="flex items-start gap-3">
                <AlertTriangle className="w-5 h-5 text-amber-500 shrink-0 mt-0.5" />
                <div>
                  <h4 className="font-bold text-amber-900 mb-1">Apostille Warning</h4>
                  <p className="text-sm text-amber-800 leading-relaxed">
                    Germany does <strong>NOT</strong> recognize standard Hague Apostilles for Indian documents. They require formal Embassy Document Verification (Urkundenüberprüfung).
                  </p>
                </div>
              </div>
            </div>
          </div>

          {/* Checklist Output */}
          <div className="w-full md:w-2/3">
            <Card className="border-border shadow-lg">
              <CardHeader className="bg-muted/50 border-b border-border">
                <CardTitle className="flex items-center gap-2">
                  <FileText className="w-5 h-5 text-primary" /> Your Required Documents
                </CardTitle>
                <CardDescription>
                  Prepare these in exact order. All copies must be notarized and translated by a sworn German translator.
                </CardDescription>
              </CardHeader>
              <CardContent className="p-0">
                <ul className="divide-y divide-border">
                  {[
                    { title: "Valid Passport", desc: "Color copy of all pages, notarized.", req: "Mandatory" },
                    { title: "Curriculum Vitae (Lebenslauf)", desc: "In German, strictly in tabular format with signature & date.", req: "Mandatory" },
                    { title: profession === "nurse" ? "BSc Nursing / GNM Degree" : "Medical Degree (MBBS/BDS)", desc: "Original requires Embassy Verification.", req: "Mandatory" },
                    { title: "Academic Transcripts", desc: "Detailed mark sheets for all years.", req: "Mandatory" },
                    { title: "Certificate of Registration", desc: `From ${indianState.charAt(0).toUpperCase() + indianState.slice(1)} Medical/Nursing Council.`, req: "Mandatory" },
                    { title: "Certificate of Good Standing", desc: "Issued by your State Council. Must be less than 3 months old at time of submission.", req: "Mandatory (Time-sensitive)" },
                    { title: "Police Clearance Certificate (PCC)", desc: "Issued by Regional Passport Office (RPO). Must be less than 3 months old.", req: "Mandatory (Time-sensitive)" },
                    { title: "Birth Certificate", desc: "Must be issued by municipal corporation with matching name.", req: "Mandatory" },
                    { title: "B2 German Certificate", desc: "From Goethe-Institut, TELC, or ÖSD.", req: "Mandatory" },
                    { title: "Medical Fitness Certificate", desc: "Ärztliche Bescheinigung. Must be less than 1 month old at submission.", req: "Mandatory (Time-sensitive)" },
                  ].map((doc, idx) => (
                    <li key={idx} className="p-4 md:p-6 flex items-start gap-4 hover:bg-muted/30 transition-colors">
                      <div className="w-6 h-6 rounded-full border-2 border-border bg-background flex items-center justify-center shrink-0 mt-0.5 print:border-black">
                        {/* Empty circle for printing checklist */}
                        <div className="w-3 h-3 rounded-full bg-transparent hover:bg-primary/20 transition-colors cursor-pointer print:hidden"></div>
                      </div>
                      <div>
                        <h4 className="font-bold text-foreground text-lg mb-1">{doc.title}</h4>
                        <p className="text-muted-foreground text-sm mb-2">{doc.desc}</p>
                        <span className={`text-xs font-bold px-2 py-1 rounded-md ${doc.req.includes('Time') ? 'bg-red-100 text-red-700' : 'bg-green-100 text-green-700'}`}>
                          {doc.req}
                        </span>
                      </div>
                    </li>
                  ))}
                </ul>
              </CardContent>
            </Card>
          </div>

        </div>
      </section>
    </div>
  );
}
